### ISSUE TITLE
VSCode storage.json location changed

### ISSUE THREAD

**Issue by evisong** [shaodahong/alfred-code#2]
Thanks for this handy workflow.

Recently I find it not working properly, and I can't find `storage.json` in the current location.

https://github.com/shaodahong/alfred-code/blob/d8e488a996a7ef579409f6494e2c0d8544064219/index.js#L9

However after a search, this file is moved to `~/Library/Application\ Support/Code/User/globalStorage/storage.json`. Fyi, the version of my VSCode for mac is `1.67.1 (Universal)`.

**Comment by shaodahong** [comment]
Thanks, I fixed it, but i lost npm 2fa so i have to wait till i get it back
